# Generated by Django 5.1 on 2024-12-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
